version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"  # expose only Nginx to the host
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist/art-gallery:/usr/share/nginx/html:ro
    depends_on:
      - backend
    networks:
      - artgallery_net

  backend:
    image: artgallery_backend:prod  # use a pre-built backend image
    environment:
      - DJANGO_DEBUG_ON=False
    secrets:
      - django_secret_key
      - postgres_db
      - postgres_user
      - postgres_password
    depends_on:
      db:
        condition: service_healthy
    networks:
      - artgallery_net

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_db
      - postgres_user
      - postgres_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - artgallery_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER_FILE -d $POSTGRES_DB_FILE"]
      interval: 5s
      timeout: 5s
      retries: 5

secrets:
  django_secret_key:
    file: ./secrets/django_secret_key.txt
  postgres_db:
    file: ./secrets/postgres_db.txt
  postgres_user:
    file: ./secrets/postgres_user.txt
  postgres_password:
    file: ./secrets/postgres_password.txt

volumes:
  postgres_data:

networks:
  artgallery_net:
    driver: overlay
    attachable: true

