# Generated by Django 5.1.4 on 2025-01-05 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='collectionartwork',
            old_name='artwork_id',
            new_name='artwork',
        ),
        migrations.RenameField(
            model_name='collectionartwork',
            old_name='collection_id',
            new_name='collection',
        ),
    ]
