# Generated by Django 5.1.4 on 2025-01-05 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_category_id_artwork_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='category',
        ),
        migrations.CreateModel(
            name='ArtworkCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.artwork')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='artwork',
            field=models.ManyToManyField(related_name='category_artworks', through='api.ArtworkCategory', to='api.artwork'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='category',
            field=models.ManyToManyField(related_name='artwork_categories', through='api.ArtworkCategory', to='api.category'),
        ),
    ]
