# Generated by Django 5.1.5 on 2025-01-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
