FROM python:3.10-slim

RUN apt-get update && apt-get install -y \
    libpq-dev \
    gnupg \
    build-essential \
    gcc \
    cmake \
    pkg-config \
    autoconf \
    automake \
    && rm -rf /var/lib/apt/lists/*

ENV MESON_SKIP_TESTS=1

WORKDIR /backend

COPY ./requirements.txt ./requirements.txt
RUN pip install --upgrade pip \
    && pip install -r requirements.txt

COPY . .

WORKDIR /backend/backendapi
EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]